### ISSUE TITLE
Foodle shutter

### ISSUE THREAD

**Issue by anditheslp** [JakeWasChosen/JakeWasChosen.github.io#34]
When I play Foodle on my iPad, the boxes in the grid look like shutter slats and I only see the row I’m typing into.  When I hit enter, the whole grid disappears and I need to hit refresh to see it.  This can’t be what you intended.  Please fix!
![3A0297F5-941A-4538-9C3C-868BC8E7A666](https://user-images.githubusercontent.com/106836779/171928595-658449c3-81be-47ff-9bcb-1a5b9a093b67.png)

**Comment by JasonLovesDoggo** [comment]
It is caused by an iOS update.
I need to research how to fix it

**Comment by anditheslp** [comment]
OK. Thanks for the quick response.  


Sent from AT&T Yahoo Mail for iPad


On Friday, June 3, 2022, 11:51 AM, Jason ***@***.***> wrote:




It is caused by an iOS update.
I need to research how to fix it

**Comment by JasonLovesDoggo** [comment]
the problem is don't own an iOS or pad device that I could debug this on.

**Comment by anditheslp** [comment]
Can you borrow one?  


Sent from AT&T Yahoo Mail for iPad


On Friday, June 3, 2022, 12:25 PM, Jason ***@***.***> wrote:




the problem is don't own an iOS or pad device that I could debug this on.

**Comment by JasonLovesDoggo** [comment]
> Can you borrow one?  

I will.. soon..

**Comment by JasonLovesDoggo** [comment]
latest commit should have fixed it.

**Comment by anditheslp** [comment]
It wasn’t fixed when I did the puzzle today.   No change at all.


Sent from AT&T Yahoo Mail for iPad


On Tuesday, June 14, 2022, 5:19 AM, Jason ***@***.***> wrote:




latest commit should have fixed it.

**Comment by JasonLovesDoggo** [comment]
Your phone has the the old version cached.
