### ISSUE TITLE
Foodle

### ISSUE THREAD

**Issue by BarbaraSullivanE** [JakeWasChosen/JakeWasChosen.github.io#37]
For the last 2 days, all the boxes in foodle fall on top of each other!!! All of my answers do so also. Nothing lights up. ????? Thanks.

**Comment by JasonLovesDoggo** [comment]
I fixed this today.
 
but your phone probably has an old version cached

**Comment by BarbaraSullivanE** [comment]
Thanks, Jason. Trying to delete my link and start again.
