### ISSUE TITLE
[BUG] ReCaptcha doesn't work on old domain

### ISSUE THREAD

**Issue by OpenSourceSimon** [JakeWasChosen/JakeWasChosen.github.io#41]
**Describe the bug**
If you go to the URL in your Twitter bio (nasoj.me/foodle), then the captcha doesn't work

**To Reproduce**
1. Go to 'https://nasoj.me/foodle'
2. Click on 'Settings -> Suggest a word'

**Screenshots**
![image](https://user-images.githubusercontent.com/65854503/190195395-81bc2e13-b5e0-46f9-893f-bb39f14a7259.png)

**Client (please complete the relevant following information):**
 - OS: Windows and Android
 - Browser: Chrome and Edge

**Comment by JasonLovesDoggo** [comment]
![Screenshot_20220914-173317.png](https://user-images.githubusercontent.com/66544866/190266750-1e2b6542-627e-4e72-b9dc-580c5cc25c39.png) fixed.
